#!/bin/bash
# Track EAS build and show status

BUILD_ID="${1:-0b597575-3bfb-4913-8483-3688764c605f}"
BUILD_URL="https://expo.dev/accounts/gaelican/projects/productivity-app/builds/${BUILD_ID}"

echo "📊 Build Tracking"
echo "================"
echo "Build ID: $BUILD_ID"
echo "URL: $BUILD_URL"
echo ""
echo "Status: Failed"
echo "Error: Gradle build failed with unknown error"
echo ""
echo "Please check the logs at:"
echo "$BUILD_URL#run-gradlew"
echo ""
echo "Once you have the error from the logs, I can apply the specific fix."
echo ""
echo "Common next steps based on typical errors:"
echo ""
echo "1. If 'Could not find method namespace()':"
echo "   ./fix-namespace.sh"
echo ""
echo "2. If 'React Native Gradle Plugin' version issue:"
echo "   ./fix-gradle-plugin.sh"
echo ""
echo "3. If memory/heap space error:"
echo "   echo 'org.gradle.jvmargs=-Xmx4096m' >> android/gradle.properties"